# -*- coding: utf-8 -*-
"""TdAI_Live_Mode_v1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyM8GI1dDfk494pC8gBRxcNTf9aBfuZS
"""

"""
This script runs TdAI in "live mode."

It pulls in the most recent 12z HRRR run and 13z NBM run, compiles the input dataset, then runs TdAI for the current and next day.
TdAI's daily performance record is kept in a spreadsheet which is used for evaluations.

"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import requests
import os
import datetime
import time
import io
import pandas as pd
import xarray as xr
import numpy as np
import re
import random

# Install cfgrib and eccodes if not already installed
try:
    import cfgrib
except ImportError:
    print("Installing cfgrib and eccodes...")
    !pip install cfgrib eccodes
    import cfgrib

"""# **Functions**"""

def seed_everything(seed=42):
    # 1. Set Python's built-in random seed
    random.seed(seed)
    # 2. Set Numpy's seed (Crucial for your jittering/noise)
    np.random.seed(seed)
    # 3. Set environment variable for any OS-level randomness
    os.environ['PYTHONHASHSEED'] = str(seed)
    print(f"✅ Random state locked at {seed}")

seed_everything(42)


def calculate_lpw_vectorized(df, all_levels):
    """
    Calculates Integrated Water Vapor (LPW) in millimeters (mm) across all
    specified pressure levels simultaneously using high-speed vectorized NumPy operations.
    Designed explicitly for input columns stored natively in Celsius.
    """
    g = 9.80665
    rho_w = 1000.0

    # Pre-allocate specific humidity arrays for each level across all rows
    q_matrix = []

    for lvl in all_levels:
        p = float(lvl)
        dpt_col = f'dpt_{lvl}'  # Ambient temp (t_col) is not mathematically required for LPW depth

        # --- AUGUST-ROCHE-MAGNUS FORMULATION (https://en.wikipedia.org/wiki/Clausius%E2%80%93Clapeyron_relation#Meteorology_and_climatology) ---
        # Takes dpt in Celsius
        e = 6.1094 * np.exp((17.625 * (df[dpt_col])) / (df[dpt_col] + 243.04))

        # Calculate mixing ratio (w) and specific humidity (q) https://glossary.ametsoc.org/wiki/specific-humidity/
        w = 0.622 * e / (p - e)
        q = w / (1.0 + w)

        q_matrix.append(q.values)

    # Shape of matrix: (num_levels, num_rows)
    q_matrix = np.array(q_matrix)

    # Initialize the integration output array
    lpw_total = np.zeros(len(df))

    # Hydrostatic integration layer-by-layer
    for i in range(len(all_levels) - 1):
        p_high = float(all_levels[i])   # Higher pressure (e.g., 1000 hPa)
        p_low = float(all_levels[i+1])  # Lower pressure (e.g., 925 hPa)

        # Pressure differential converted to Pascals (1 hPa = 100 Pa)
        dp = (p_high - p_low) * 100.0

        # Average specific humidity across the bounded layer
        q_avg = (q_matrix[i] + q_matrix[i+1]) / 2.0

        # Hydrostatic integration equation mapping to mm depth
        lpw_total += (q_avg * dp) / (g * rho_w) * 1000.0

    return lpw_total


def calculate_lapse_rate_vectorized(df, p_bottom, p_top):
  """
  Calculates the vertical temperature lapse rate (°C/km) between any two pressure
  levels dynamically using the Hypsometric Equation to determine layer thickness.

  Parameters:
  -----------
  df : pandas.DataFrame
      The pivoted HRRR DataFrame containing columns in 't_LEVEL' format (Celsius).
  p_bottom : int
      The pressure level at the bottom of the layer (e.g., 1000).
  p_top : int
      The pressure level at the top of the layer (e.g., 850).

  Returns:
  --------
  pandas.Series or np.nan
      A vectorized series representing the lapse rate in °C/km.
  """
  t_bottom_col = f't_{p_bottom}'
  t_top_col = f't_{p_top}'

  # 1. Enforce safety validation check for missing levels
  if t_bottom_col not in df.columns or t_top_col not in df.columns:
      return np.nan

  # 2. Extract ambient temperatures at the boundaries (assumed already in Celsius)
  t_bottom = df[t_bottom_col]
  t_top = df[t_top_col]

  # 3. Calculate raw temperature difference (Bottom - Top)
  # Positive = temperature cooling with height
  delta_t = t_bottom - t_top

  # 4. DYNAMIC GEOPOTENTIAL THICKNESS (The Hypsometric Equation)
  # Rd = 287.05 J/(kg*K) [Gas constant for dry air]
  # g  = 9.80665 m/s^2  [Standard gravitational acceleration]
  # Convert mean layer temperature to Kelvin
  t_mean_k = ((t_bottom + t_top) / 2.0) + 273.15

  # Calculate layer thickness in meters, then divide by 1000.0 for kilometers (dz_km)
  dz_meters = (287.05 * t_mean_k / 9.80665) * np.log(float(p_bottom) / float(p_top))
  dz_km = dz_meters / 1000.0

  # 5. Compute the lapse rate
  lapse_rate = delta_t / dz_km

  return lapse_rate

"""# **Load in 12z HRRR Data**"""

import datetime
import os
import requests
import pandas as pd  # 🚀 Added missing pandas import
import xarray as xr
import numpy as np

# KCAR ASOS coordinates
kcar_lat, kcar_lon = 46.870478, -68.017225

# Function to download HRRR GRIB2 file
def download_hrrr_grib(date_str, run_hour='12', forecast_hour=0):
    base_url = f"https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/hrrr.{date_str}/conus/"
    filename = f"hrrr.t{run_hour}z.wrfprsf{forecast_hour:02d}.grib2"
    url = base_url + filename
    local_path = filename

    print(f"Attempting to download: {url}")
    try:
        response = requests.get(url, stream=True, timeout=30)
        response.raise_for_status() # Raise an exception for HTTP errors

        with open(local_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Successfully downloaded {filename}")
        return local_path
    except requests.exceptions.RequestException as e:
        print(f"Failed to download {filename} from {url}: {e}")
        return None

# Try to get today's 12z HRRR, if not fully available out to F33 yet, fall back to yesterday's complete run
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)

date_strs = [today.strftime('%Y%m%d'), yesterday.strftime('%Y%m%d')]
forecast_hours = [9, 33]

grib_files = {}

# 🚀 FIX 1: Initialize a list to collect DataFrames from each forecast hour outside the loop
all_forecast_dfs = []

# CHRONOLOGICAL SEARCH ENFORCING ALL-OR-NOTHING PER INITIALIZATION TIME
for ds_date in date_strs:
    success = True
    temp_files = {}
    for fhr in forecast_hours:
        local_file = download_hrrr_grib(ds_date, run_hour='12', forecast_hour=fhr)
        if local_file:
            temp_files[fhr] = local_file
        else:
            success = False
            for f in temp_files.values():
                if os.path.exists(f):
                    os.remove(f)
            break
    if success:
        grib_files = temp_files
        break

if not grib_files:
    print("Could not download the latest 12z HRRR GRIB2 files for hours 9 and 33.")
else:
    # 🚀 LOOP AND PROCESS EACH TARGET FORECAST HOUR INDEPENDENTLY
    for fhr, grib_file in grib_files.items():

        # Open the GRIB2 file, filtering immediately for isobaric levels.
        with xr.open_dataset(grib_file, engine='cfgrib', backend_kwargs={'filter_by_keys': {'typeOfLevel': 'isobaricInhPa'}}) as ds_filtered:

             # Extract the scalar valid_time and format it nicely
            valid_time_str = pd.Timestamp(ds_filtered['valid_time'].values).strftime('%Y-%m-%d %H:%M')

            print(f"\n==================================================================")
            print(f"📦 PROCESSING HRRR FORECAST HOUR: F{fhr:02d} AT VALID TIME {valid_time_str}")
            print(f"==================================================================")

            # Convert longitude to the 0-360° East convention used by NOAA GRIB2
            kcar_lon_360 = kcar_lon + 360.0 if kcar_lon < 0 else kcar_lon

            # Calculate the Euclidean distance matrix between HRRR grid points and KCAR
            delta_lat = ds_filtered['latitude'] - kcar_lat
            delta_lon = ds_filtered['longitude'] - kcar_lon_360
            squared_distance = (delta_lat ** 2) + (delta_lon ** 2)

            # Convert to numpy to quickly find the flat index of the absolute minimum distance
            dist_array = squared_distance.to_numpy()

            # Unravel the flat index into the exact 2D (y, x) array grid coordinates
            y_idx, x_idx = np.unravel_index(np.nanargmin(dist_array), dist_array.shape)

            # Print out the location of the nearest HRRR grid point
            nearest_lat = ds_filtered['latitude'].values[y_idx, x_idx]
            nearest_lon = ds_filtered['longitude'].values[y_idx, x_idx] - 360.0
            print(f"📍 Selected data from nearest HRRR grid point location: ({nearest_lat:.4f}, {nearest_lon:.4f})")

            # Extract the single column vertical profile using .isel index selection
            ds_point = ds_filtered.isel(y=y_idx, x=x_idx)

            # Store profiles in local variables for this specific file to avoid cross-over overwriting
            temperature_profile = ds_point['t'].to_numpy()
            dewpoint_profile = ds_point['dpt'].to_numpy()
            pressure_levels = ds_point['isobaricInhPa'].to_numpy()

            # Trim off data above 500mb (keep pressure values from 500mb down to the ground)
            lower_trop_mask = (pressure_levels >= 500) & (pressure_levels <= 1000)
            pressure_levels = pressure_levels[lower_trop_mask]
            temperature_profile = temperature_profile[lower_trop_mask]
            dewpoint_profile = dewpoint_profile[lower_trop_mask]

            # Broadcast the valid time string to match the length of the filtered profile arrays
            valid_time_column = np.full(len(pressure_levels), valid_time_str)

            # Build the dataframe for *this hour only* and append it to our collector list
            hour_df = pd.DataFrame({
                'valid_time': valid_time_column,
                'HRRR Pressure (hPa)': pressure_levels,
                'HRRR Temperature (K)': temperature_profile,
                'HRRR Dewpoint (K)': dewpoint_profile
            })

            # Add individual forecast hour dataframes to the master list for concatenation to a df at the end
            all_forecast_dfs.append(hour_df)

        # Clean up the downloaded GRIB file before stepping to the next hour index
        if os.path.exists(grib_file):
            os.remove(grib_file)
            print(f"Cleaned up temporary file: {grib_file}")

    # Once the loop is totally complete, concatenate all hours into one master DataFrame
    master_hrrr_profiles_df = pd.concat(all_forecast_dfs, ignore_index=True)

    # --- VECTORIZED RELATIVE HUMIDITY CALCULATION ---
    # Convert Temperature and Dewpoint from Kelvin to Celsius (ensuring float type)
    t_celsius = master_hrrr_profiles_df['HRRR Temperature (K)'].astype(float) - 273.15
    dp_celsius = master_hrrr_profiles_df['HRRR Dewpoint (K)'].astype(float) - 273.15

    # Compute Saturation Vapor Pressure (es) and Actual Vapor Pressure (e)
    es = np.exp((17.625 * t_celsius) / (243.04 + t_celsius))
    e = np.exp((17.625 * dp_celsius) / (243.04 + dp_celsius))

    # Calculate RH (%) and clip boundaries between 0.0% and 100.0%
    master_hrrr_profiles_df['HRRR RH (%)'] = round(np.clip(100 * (e / es), 0.0, 100.0), 1)

    print("\n==================================================================")
    print("✨ MASTER COMBINED HRRR PROFILE DATAFRAME SUCCESSFULY COMPILED:")
    print("==================================================================")
    print(master_hrrr_profiles_df.to_string(index=False))
    print("==================================================================")

"""# **Load in 13z NBM data**"""

import datetime
import re
import pandas as pd
import numpy as np
import requests

def get_nbm_13z_bulletin(date_str):
    """Attempts to download the NBM 13z hourly text bulletin for a given date string."""
    base_url = f"https://nomads.ncep.noaa.gov/pub/data/nccf/com/blend/prod/blend.{date_str}/13/text/"
    filename = "blend_nbstx.t13z"
    url = base_url + filename

    print(f"📡 Requesting NBM Text Feed: {url}")
    try:
        response = requests.get(url, timeout=15)
        if response.status_code == 200:
            print(f"   ✅ Successfully fetched 13z NBM data for {date_str}.")
            return response.text
        else:
            print(f"   ⚠️ File not available for {date_str} (Status: {response.status_code})")
            return None
    except Exception as e:
        print(f"   ❌ Download error: {e}")
        return None

# --- 1. DOWNLOAD LOGIC WITH BACKUP FALLBACK ---
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
date_candidates = [today.strftime('%Y%m%d'), yesterday.strftime('%Y%m%d')]

bulletin_text = None
successful_date_str = None

for date_str in date_candidates:
    bulletin_text = get_nbm_13z_bulletin(date_str)
    if bulletin_text:
        successful_date_str = date_str  # 🚀 Save the base string for datetime reconstruction
        break

if not bulletin_text:
    raise RuntimeError("Could not retrieve the 13z NBM bulletin from NOMADS for today or yesterday.")

# --- 2. ISOLATE THE KCAR BLOCK ---
print("\n🔍 Scanning bulletin for KCAR (Caribou, Maine)...")
lines = bulletin_text.split('\n')
kcar_lines = []
in_kcar_block = False

for line in lines:
    if "KCAR" in line and "NBM" in line:
        in_kcar_block = True

    if in_kcar_block:
        kcar_lines.append(line)
        if len(kcar_lines) > 2 and (line.strip() == "" or line.startswith('#') or "STATION" in line):
            if "STATION" in line or line.startswith('#'):
                kcar_lines.pop()
            break

if not kcar_lines:
    raise ValueError("Could not locate the KCAR data block inside the NBM bulletin text.")

# --- 3. PARSE WEATHER ELEMENTS FROM TEXT GRID ---
print("📊 Extracting meteorological targets...")
parsed_data = {}
targets = {
    'UTC': 'UTC Hour',
    'TMP': 'NBM Temperature (F)',
    'DPT': 'NBM Dewpoint (F)',
    'SKY': 'NBM Cloud Cover (%)',
    'WDR': 'NBM Wind Direction (tens deg)',
    'WSP': 'NBM Wind Speed (kts)',
    'MHT': 'NBM Mixing Height (100s ft)'
}

for line in kcar_lines:
    tokens = line.split()
    if not tokens: continue
    element = tokens[0]
    if element in targets:
        values = []
        for val in tokens[1:]:
            try:
                values.append(int(val))
            except ValueError:
                try:
                    values.append(float(val))
                except ValueError:
                    values.append(None)
        parsed_data[targets[element]] = values

# Create base DataFrame
nbm_df = pd.DataFrame(parsed_data)

# --- 4. 🚀 NEW: CHRONOLOGICAL VALID_TIME CONSTRUCTION WITH UTC ROLLOVER HANDLING ---
init_date = datetime.datetime.strptime(successful_date_str, '%Y%m%d')
valid_times = []
current_date = init_date
previous_hour = -1

for hr in nbm_df['UTC Hour']:
    if hr is None:
        valid_times.append(pd.NaT)
        continue

    # If the hour steps backward (e.g., from 23 to 00), we crossed into the next calendar day
    if previous_hour != -1 and hr < previous_hour:
        current_date += datetime.timedelta(days=1)

    v_time = current_date.replace(hour=hr, minute=0, second=0, microsecond=0)
    valid_times.append(v_time)
    previous_hour = hr

# Inject the true datetime series
nbm_df['valid_time'] = pd.to_datetime(valid_times)

# --- 5. METEOROLOGICAL EXPANSIONS ---
if 'NBM Wind Direction (tens deg)' in nbm_df.columns:
    nbm_df['NBM Wind Direction (deg)'] = nbm_df['NBM Wind Direction (tens deg)'] * 10

if 'NBM Mixing Height (100s ft)' in nbm_df.columns:
    nbm_df['NBM Mixing Height (100s ft AGL)'] = nbm_df['NBM Mixing Height (100s ft)']

# --- 6. VECTORIZED SURFACE RELATIVE HUMIDITY CALCULATION ---
if 'NBM Temperature (F)' in nbm_df.columns and 'NBM Dewpoint (F)' in nbm_df.columns:
    # Convert NBM parameters to Celsius for the thermodynamic calculation
    nbm_tc = (nbm_df['NBM Temperature (F)'] - 32) * (5.0 / 9.0)
    nbm_tdc = (nbm_df['NBM Dewpoint (F)'] - 32) * (5.0 / 9.0)

    # Calculate Saturation Vapor Pressure (es) and Vapor Pressure (e)
    nbm_es = np.exp((17.625 * nbm_tc) / (243.04 + nbm_tc))
    nbm_e = np.exp((17.625 * nbm_tdc) / (243.04 + nbm_tdc))

    # Generate and clamp the Relative Humidity percentage column
    nbm_df['NBM RH (%)'] = round(np.clip(100 * (nbm_e / nbm_es), 0.0, 100.0), 1)

# --- 7. 🚀 NEW: CONVECTIVE WINDOW ISOLATION (FILTER FOR 21Z ONLY) ---
print("⏰ Filtering grid for 21Z peak afternoon mixing slices...")
nbm_df = nbm_df[nbm_df['valid_time'].dt.hour == 21].copy()

# Reorder columns to match your model training format
column_order = [
    'valid_time',
    'NBM Temperature (F)',
    'NBM Dewpoint (F)',
    'NBM Cloud Cover (%)',
    'NBM Mixing Height (100s ft AGL)',
    'NBM Wind Speed (kts)',
    'NBM Wind Direction (deg)',
    'NBM RH (%)'
]
nbm_df = nbm_df[[col for col in column_order if col in nbm_df.columns]]

print("\n✨ KCAR REAL-TIME NBM INPUT VECTOR COMPILED SUCCESSFULY:")
print("─" * 95)
print(nbm_df.to_string(index=False))
print("─" * 95)

"""# **Compile the Input Dataset**"""

print("\n🔗 Compiling and aligning model input vector matrices...")

# Ensure synchronization datatypes for the merge key
nbm_df['valid_time'] = pd.to_datetime(nbm_df['valid_time'])
master_hrrr_profiles_df['valid_time'] = pd.to_datetime(master_hrrr_profiles_df['valid_time'])

# DEFENSIVE STEP: Explicitly force all weather variables to numeric types before pivoting
numeric_vars = ['HRRR Pressure (hPa)', 'HRRR Temperature (K)', 'HRRR Dewpoint (K)', 'HRRR RH (%)']
for var in numeric_vars:
    if var in master_hrrr_profiles_df.columns:
        master_hrrr_profiles_df[var] = pd.to_numeric(master_hrrr_profiles_df[var], errors='coerce')

# 1. PIVOT LONG PROFILE FOR ALL NECESSARY METRICS SIMULTANEOUSLY
hrrr_pivoted = master_hrrr_profiles_df.pivot(
    index='valid_time',
    columns='HRRR Pressure (hPa)',
    values=['HRRR Temperature (K)', 'HRRR Dewpoint (K)', 'HRRR RH (%)']
)

# 2. FLATTEN THE MULTIINDEX COLUMNS TO MATCH THE CUSTOM METEOROLOGICAL FUNCTIONS
new_columns = []
for var, lvl in hrrr_pivoted.columns:
    lvl_int = int(float(lvl))
    if var == 'HRRR Temperature (K)':
        new_columns.append(f"t_{lvl_int}")
    elif var == 'HRRR Dewpoint (K)':
        new_columns.append(f"dpt_{lvl_int}")
    elif var == 'HRRR RH (%)':
        new_columns.append(f"rh_{lvl_int}")

hrrr_pivoted.columns = new_columns
hrrr_pivoted = hrrr_pivoted.reset_index()

# 🚀 3. UNIT CONVERSIONS: CONVERT THERMAL PROFILES TO CELSIUS (With explicit numeric enforcement)
thermal_cols = [c for c in hrrr_pivoted.columns if c.startswith('t_') or c.startswith('dpt_')]
for col in thermal_cols:
    hrrr_pivoted[col] = pd.to_numeric(hrrr_pivoted[col], errors='coerce')

# Convert Kelvin to Celsius safely
hrrr_pivoted[thermal_cols] = hrrr_pivoted[thermal_cols] - 273.15

# 4. EXTRACT LEVEL STRUCTURE AND EXECUTE CUSTOM VECTORIZED MET FUNCTIONS
all_levels = sorted(
    [int(col.split('_')[1]) for col in hrrr_pivoted.columns if col.startswith('t_')],
    reverse=True
)

# Compute LPW and Lapse rates using your custom function signatures
hrrr_pivoted['hrrr_lpw (mm)'] = calculate_lpw_vectorized(hrrr_pivoted, all_levels)
hrrr_pivoted['1000mb-700mb Lapse Rate (C/km)'] = calculate_lapse_rate_vectorized(hrrr_pivoted, 1000, 700)
hrrr_pivoted['700mb-500mb Lapse Rate (C/km)'] = calculate_lapse_rate_vectorized(hrrr_pivoted, 700, 500)

# 5. UNIFY NBM SURFACE CONDITIONS AND PIVOTED HRRR LAYERS
master_input_df = pd.merge(nbm_df, hrrr_pivoted, on='valid_time', how='inner')

# 6. CALCULATE CYCLICAL SEASONAL COMPONENTS
doy = master_input_df['valid_time'].dt.dayofyear
master_input_df['sin_season'] = np.sin(2 * np.pi * doy / 365.25)
master_input_df['cos_season'] = np.cos(2 * np.pi * doy / 365.25)

# =========================================================================
# 7. ORDER AND SELECT OUTPUT COLUMNS
# =========================================================================
csv_column_order = [
    'valid_time', 'NBM Temperature (F)', 'NBM Dewpoint (F)', 'NBM Cloud Cover (%)',
    'NBM Mixing Height (100s ft AGL)', 'NBM Wind Speed (kts)', 'NBM Wind Direction (deg)',
    'hrrr_lpw (mm)', 'rh_1000', 'rh_975', 'rh_950', 'rh_925',
    'rh_900', 'rh_875', 'rh_850', 'rh_825', 'rh_800', 'rh_775', 'rh_750', 'rh_725',
    'rh_700', 'rh_675', 'rh_650', 'rh_625', 'rh_600', 'rh_575', 'rh_550', 'rh_525',
    'rh_500', '1000mb-700mb Lapse Rate (C/km)', '700mb-500mb Lapse Rate (C/km)',
    'NBM RH (%)', 'sin_season', 'cos_season'
]

# Rearrange columns safely (this naturally filters out the temporary t_ and dpt_ columns)
master_input_df = master_input_df[[col for col in csv_column_order if col in master_input_df.columns]]

print("\n✨ TdAI OPERATIONAL INPUT DATASET COMPILED SUCCESSFULLY:")
print("─" * 100)
print(master_input_df.to_string(index=False))
print("─" * 100)

"""# **Run TdAI**"""

import joblib

print("\n🤖 Initializing TdAI Live Inference Engine...")

# 1. Define paths to your saved model files
base_path = "/content/drive/MyDrive/Fire Weather Focal Point/TdAI_Project/Development/Data/"

model_import_path = os.path.join(base_path, "tdai_gbdt_model.joblib")
features_import_path = os.path.join(base_path, "model_feature_schema.joblib")

# Verification check to ensure files are present before proceeding
if not (os.path.exists(model_import_path) and os.path.exists(features_import_path)):
    print(f"❌ Error: Model files or schema sheets missing at deployment location.")
else:
    # 2. Load the binary assets back into memory
    live_model = joblib.load(model_import_path)
    trained_feature_order = joblib.load(features_import_path)
    print("   ✅ Pre-trained GBDT weights and feature schemas loaded successfully.")

    # 3. Isolate the feature matrix from the master compilation frame
    # We create a copy and set valid_time as the index so it doesn't feed as a feature
    X_live = master_input_df.set_index('valid_time') if 'valid_time' in master_input_df.columns else master_input_df.copy()

    # 4. 🚀 BULLETPROOF ALIGNMENT BIAS GUARD:
    # Force the live columns to match the exact sorting order the model saw during training
    try:
        X_live = X_live[trained_feature_order]
    except KeyError as e:
        missing_cols = set(trained_feature_order) - set(X_live.columns)
        raise KeyError(f"❌ Structural Failure: Live data is missing features required by the model: {missing_cols}")

    # 5. Generate the Predicted Target Error
    # The output represents the predicted value of: (NBM Dewpoint - ASOS Ground Truth)
    predicted_target_error = live_model.predict(X_live)

    # 6. Apply the Correction Back to the NBM Baseline
    # Algebra: Since Target Error = NBM - ASOS, then Corrected ASOS Estimate = NBM - Target Error
    master_input_df['TdAI Predicted Bias (F)'] = predicted_error = predicted_target_error
    master_input_df['TdAI Corrected Dewpoint (F)'] = master_input_df['NBM Dewpoint (F)'] - master_input_df['TdAI Predicted Bias (F)']

    # Round outputs for clean display and grid integration
    master_input_df['TdAI Corrected Dewpoint (F)'] = master_input_df['TdAI Corrected Dewpoint (F)'].round(1)
    master_input_df['TdAI Predicted Bias (F)'] = master_input_df['TdAI Predicted Bias (F)'].round(1)

    # 7. OUTPUT FINAL METEOROLOGICAL DISPATCH REPORT
    print("\n======================================================================================")
    print("🔥 TdAI REAL-TIME POST-PROCESSED FORECAST DISPATCH FOR KCAR")
    print("======================================================================================")

    display_cols = [
        'valid_time',
        'NBM Temperature (F)',
        'NBM RH (%)',
        'NBM Dewpoint (F)',
        'TdAI Predicted Bias (F)',
        'TdAI Corrected Dewpoint (F)'
    ]

    print(master_input_df[display_cols].to_string(index=False))
    print("======================================================================================")

master_input_df

"""# **Validate TdAI and Log Forecast & Verification**"""

# =========================================================================
# 📊 STEP 5: AUTOMATED REAL-TIME MULTI-ROW FORECAST VALIDATION ENGINE
# =========================================================================
import io
import os
import pandas as pd
import numpy as np
import datetime
import requests

# Import Google Colab authentication and gspread libraries for live Google Sheets logging
from google.colab import auth
import gspread
from google.auth import default

print("\n📊 Initializing Automated Forecast Validation & Logging Engine...")

# 1. Trigger the user credentials verification gate within the Colab instance
print("📡 Connecting to Google Sheets cloud repository...")
try:
    auth.authenticate_user()
    creds, _ = default()
    gc = gspread.authorize(creds)

    spreadsheet_name = "TdAI Operational Log"

    # Attempt to open the target sheet document. Initialize it if it does not exist yet.
    try:
        sh = gc.open(spreadsheet_name)
        worksheet = sh.get_worksheet(0)
        print(f"   ✅ Connected successfully to existing Google Sheet: '{spreadsheet_name}'")
    except gspread.exceptions.SpreadsheetNotFound:
        print(f"   📝 Google Sheet '{spreadsheet_name}' not found. Spawning new file allocation...")
        sh = gc.create(spreadsheet_name)
        worksheet = sh.get_worksheet(0)
        print(f"   ✅ Created and initialized fresh Google Sheet workbook: '{spreadsheet_name}'")

    # Pull current cells into a DataFrame layout matrix
    all_values = worksheet.get_all_values()
    if len(all_values) >= 1:
        headers = all_values[0]
        if len(all_values) > 1:
            existing_log_df = pd.DataFrame(all_values[1:], columns=headers)
        else:
            existing_log_df = pd.DataFrame(columns=headers)
    else:
        # Default column schema if the sheet is brand new and completely empty
        headers = [
            'valid_time', 'TdAI Run Time (UTC)', 'NBM Temperature (F)', 'NBM RH (%)',
            'NBM Dewpoint (F)', 'TdAI Predicted Bias (F)', 'TdAI Corrected Dewpoint (F)',
            'ASOS Ground Truth Dewpoint (F)', 'Raw NBM Error (F)', 'Post TdAI Error (F)',
            'TdAI Skill Score (%)'
        ]
        existing_log_df = pd.DataFrame(columns=headers)

    # 🚀 FIX: Loop through ALL rows in master_input_df instead of hardcoding .iloc[0]
    new_rows_list = []
    current_time_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)

    for idx in range(len(master_input_df)):
        row_data = master_input_df.iloc[idx]
        forecast_valid_time = row_data['valid_time']

        print(f"\nProcessing forecast row {idx + 1}/{len(master_input_df)}:")
        print(f"   └── Forecast valid time : {forecast_valid_time.strftime('%Y-%m-%d %H:%M UTC')}")
        print(f"   └── System clock time   : {current_time_utc.strftime('%Y-%m-%d %H:%M UTC')}")

        # Initialize baseline log parameters for this row
        log_row = {
            'valid_time': forecast_valid_time.strftime('%Y-%m-%d %H:%M:%S'),
            'TdAI Run Time (UTC)': current_time_utc.strftime('%Y-%m-%d %H:%M UTC'),
            'NBM Temperature (F)': row_data['NBM Temperature (F)'],
            'NBM RH (%)': row_data['NBM RH (%)'],
            'NBM Dewpoint (F)': row_data['NBM Dewpoint (F)'],
            'TdAI Predicted Bias (F)': row_data['TdAI Predicted Bias (F)'],
            'TdAI Corrected Dewpoint (F)': row_data['TdAI Corrected Dewpoint (F)'],
            'ASOS Ground Truth Dewpoint (F)': np.nan,
            'Raw NBM Error (F)': np.nan,
            'Post TdAI Error (F)': np.nan,
            'TdAI Skill Score (%)': np.nan
        }

        # State Check: Is the forecast window in the future or the past?
        if current_time_utc < forecast_valid_time + datetime.timedelta(minutes=15):
            print("   ⏳ Verification Status: STANDBY")
            print(f"      └── Reason: The forecast validation window has not been reached yet.")
            print(f"      └── Action: Logging forecast fields. Verification parameters will remain blank.")
        else:
            print("   📡 Forecast hour is in the past. Fetching KCAR ASOS ground-truth observation...")
            start_date = forecast_valid_time - datetime.timedelta(days=1)
            end_date = forecast_valid_time + datetime.timedelta(days=1)
            station_iem = 'CAR'

            asos_url = (
                f"https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?"
                f"station={station_iem}&data=dwpf&"
                f"year1={start_date.year}&month1={start_date.month}&day1={start_date.day}&"
                f"year2={end_date.year}&month2={end_date.month}&day2={end_date.day}&"
                f"tz=UTC&format=comma"
            )

            try:
                response = requests.get(asos_url, timeout=20)
                response.raise_for_status()
                asos_df = pd.read_csv(io.StringIO(response.text), comment='#')

                if asos_df.empty or 'dwpf' not in asos_df.columns:
                    print("      ⚠️ Warning: No observations found in the IEM registry for this window.")
                else:
                    asos_df['valid_dt'] = pd.to_datetime(asos_df['valid'])
                    asos_df['rounded_valid_time'] = asos_df['valid_dt'].dt.round('h')
                    target_obs = asos_df[asos_df['rounded_valid_time'] == forecast_valid_time].copy()

                    if target_obs.empty:
                        print(f"      ⚠️ Warning: The specific 21Z observation row was missing from the server.")
                    else:
                        target_obs['dwpf_numeric'] = pd.to_numeric(target_obs['dwpf'], errors='coerce')
                        valid_reports = target_obs.dropna(subset=['dwpf_numeric'])

                        if valid_reports.empty:
                            print(f"      ⚠️ Warning: All observations at this hour are currently masked as missing ('M').")
                        else:
                            asos_ground_truth = valid_reports['dwpf_numeric'].iloc[0]

                            # Calculate errors and forecast skill score metrics
                            raw_nbm_error = log_row['NBM Dewpoint (F)'] - asos_ground_truth
                            post_tdai_error = log_row['TdAI Corrected Dewpoint (F)'] - asos_ground_truth
                            abs_nbm = abs(raw_nbm_error)
                            abs_tdai = abs(post_tdai_error)
                            hour_skill_score = (1.0 - (abs_tdai / abs_nbm)) * 100 if abs_nbm > 0 else 0.0

                            # Update our logging row dictionary with the live validation metrics
                            log_row['ASOS Ground Truth Dewpoint (F)'] = asos_ground_truth
                            log_row['Raw NBM Error (F)'] = round(raw_nbm_error, 2)
                            log_row['Post TdAI Error (F)'] = round(post_tdai_error, 2)
                            log_row['TdAI Skill Score (%)'] = round(hour_skill_score, 1)

                            # Print Text Verification Report
                            print("   " + "═"*84)
                            print(f"   📊 POST-EVENT VERIFICATION DISPATCH REPORT FOR KCAR")
                            print("   " + "═"*84)
                            print(f"      🔹 Observed ASOS Ground Truth Dewpoint : {asos_ground_truth:.1f}°F")
                            print(f"      🔹 Original NBM Baseline Dewpoint       : {log_row['NBM Dewpoint (F)']:.1f}°F  (Error: {raw_nbm_error:+.1f}°F)")
                            print(f"      🔹 TdAI Post-Processed Dewpoint         : {log_row['TdAI Corrected Dewpoint (F)']:.1f}°F  (Error: {post_tdai_error:+.1f}°F)")
                            print("      " + "─"*78)

                            if abs_tdai < abs_nbm:
                                print(f"      🚀 SUCCESS: TdAI trimmed forecast error by {abs_nbm - abs_tdai:.1f}°F ({hour_skill_score:.1f}% Improvement).")
                            elif abs_tdai == abs_nbm:
                                print(f"      🤝 TIE: TdAI matched the baseline NBM forecast exactly.")
                            else:
                                print(f"      ⚠️ OVER-CORRECTION: TdAI increased error by {abs_tdai - abs_nbm:.1f}°F at this specific hour setup.")
                            print("   " + "═"*84)

            except Exception as e:
                print(f"      ❌ Network error during ASOS validation query: {e}")
                print("      └── Action: Proceeding to log forecast fields only.")

        new_rows_list.append(log_row)

    # Convert our collected new rows list into a structured DataFrame
    new_entry_df = pd.DataFrame(new_rows_list)

    # Align headers to ensure dataframe concatenation runs smoothly
    for col in new_entry_df.columns:
        if col not in existing_log_df.columns:
            existing_log_df[col] = np.nan

    # Enforce string serialization layout for precise deduplication evaluation matching
    new_entry_df['valid_time'] = pd.to_datetime(new_entry_df['valid_time']).dt.strftime('%Y-%m-%d %H:%M:%S')
    if 'valid_time' in existing_log_df.columns and not existing_log_df.empty:
        existing_log_df['valid_time'] = pd.to_datetime(existing_log_df['valid_time'], errors='coerce').dt.strftime('%Y-%m-%d %H:%M:%S')

    # Combine old historical records with the new run log entries
    combined_log_df = pd.concat([existing_log_df, new_entry_df], ignore_index=True)

    # 🚀 UNIQUE COMPOSITE GUARD: Never log rows with identical 'valid_time' AND 'TdAI Run Time (UTC)' twice
    combined_log_df = combined_log_df.drop_duplicates(subset=['valid_time', 'TdAI Run Time (UTC)'], keep='last')

    # Format NaNs into empty strings to clear out Google Sheet grid cell displays beautifully
    combined_log_df = combined_log_df.fillna("")

    # Clear old cell contents and push the complete data matrix back up to the cloud sheet
    worksheet.clear()
    data_to_write = [combined_log_df.columns.tolist()] + combined_log_df.values.tolist()
    worksheet.update('A1', data_to_write)

    print(f"\n💾 Google Sheets Ledger Synchronized! Workbook: '{spreadsheet_name}'")
    print(f"   └── Total continuous unique metrics row records: {len(combined_log_df)}\n")

except Exception as sheets_err:
    print(f"❌ Operational Failure: Cloud sync to Google Sheets aborted: {sheets_err}")

# =========================================================================
# 📊 STEP 5: AUTOMATED REAL-TIME FORECAST VALIDATION & LOGGING ENGINE
# =========================================================================
import io
import os
import pandas as pd
import numpy as np
import datetime
import requests

print("\n📊 Initializing Automated Forecast Validation & Logging Engine...")

# 1. Base path for your Google Drive log destination
base_path = "/content/drive/MyDrive/Fire Weather Focal Point/TdAI_Project/Development/Data/"
output_csv_path = os.path.join(base_path, "TdAI_Operational_Log.csv")

# 2. Extract current row metadata and system clock time in UTC
forecast_valid_time = master_input_df['valid_time'].iloc[0]
current_time_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)

print(f"   └── Forecast valid time : {forecast_valid_time.strftime('%Y-%m-%d %H:%M UTC')}")
print(f"   └── System clock time   : {current_time_utc.strftime('%Y-%m-%d %H:%M UTC')}")

# Initialize baseline log parameters (shared across both future and past runs)
log_row = {
    'valid_time': forecast_valid_time.strftime('%Y-%m-%d %H:%M:%S'),
    'TdAI Run Time (UTC)': current_time_utc.strftime('%Y-%m-%d %H:%M UTC'),
    'NBM Temperature (F)': master_input_df['NBM Temperature (F)'].iloc[0],
    'NBM RH (%)': master_input_df['NBM RH (%)'].iloc[0],
    'NBM Dewpoint (F)': master_input_df['NBM Dewpoint (F)'].iloc[0],
    'TdAI Predicted Bias (F)': master_input_df['TdAI Predicted Bias (F)'].iloc[0],
    'TdAI Corrected Dewpoint (F)': master_input_df['TdAI Corrected Dewpoint (F)'].iloc[0],
    'ASOS Ground Truth Dewpoint (F)': np.nan,
    'Raw NBM Error (F)': np.nan,
    'Post TdAI Error (F)': np.nan,
    'TdAI Skill Score (%)': np.nan
}

# 3. State Check: Is the forecast window in the future or the past?
if current_time_utc < forecast_valid_time + datetime.timedelta(minutes=15):
    print("\n⏳ Verification Status: STANDBY")
    print(f"   └── Reason: The forecast validation window has not been reached yet.")
    print(f"   └── Action: Logging forecast fields. Verification parameters will remain blank.")
    has_valid_verification = False
    run_logging = True
else:
    print("\n📡 Forecast hour is in the past. Fetching KCAR ASOS ground-truth observation...")
    run_logging = True  # We will log the outcome

    start_date = forecast_valid_time - datetime.timedelta(days=1)
    end_date = forecast_valid_time + datetime.timedelta(days=1)
    station_iem = 'CAR'

    asos_url = (
        f"https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?"
        f"station={station_iem}&data=dwpf&"
        f"year1={start_date.year}&month1={start_date.month}&day1={start_date.day}&"
        f"year2={end_date.year}&month2={end_date.month}&day2={end_date.day}&"
        f"tz=UTC&format=comma"
    )

    try:
        response = requests.get(asos_url, timeout=20)
        response.raise_for_status()
        asos_df = pd.read_csv(io.StringIO(response.text), comment='#')

        if asos_df.empty or 'dwpf' not in asos_df.columns:
            print("   ⚠️ Warning: No observations found in the IEM registry for this window.")
            has_valid_verification = False
        else:
            asos_df['valid_dt'] = pd.to_datetime(asos_df['valid'])
            asos_df['rounded_valid_time'] = asos_df['valid_dt'].dt.round('h')
            target_obs = asos_df[asos_df['rounded_valid_time'] == forecast_valid_time].copy()

            if target_obs.empty:
                print(f"   ⚠️ Warning: The specific 21Z observation row was missing from the server.")
                has_valid_verification = False
            else:
                target_obs['dwpf_numeric'] = pd.to_numeric(target_obs['dwpf'], errors='coerce')
                valid_reports = target_obs.dropna(subset=['dwpf_numeric'])

                if valid_reports.empty:
                    print(f"   ⚠️ Warning: All observations at this hour are currently masked as missing ('M').")
                    has_valid_verification = False
                else:
                    asos_ground_truth = valid_reports['dwpf_numeric'].iloc[0]
                    has_valid_verification = True

                if has_valid_verification:
                    # Calculate errors and forecast skill score metrics
                    raw_nbm_error = log_row['NBM Dewpoint (F)'] - asos_ground_truth
                    post_tdai_error = log_row['TdAI Corrected Dewpoint (F)'] - asos_ground_truth
                    abs_nbm = abs(raw_nbm_error)
                    abs_tdai = abs(post_tdai_error)
                    hour_skill_score = (1.0 - (abs_tdai / abs_nbm)) * 100 if abs_nbm > 0 else 0.0

                    # 🚀 Update our logging row dictionary with the live validation metrics
                    log_row['ASOS Ground Truth Dewpoint (F)'] = asos_ground_truth
                    log_row['Raw NBM Error (F)'] = round(raw_nbm_error, 2)
                    log_row['Post TdAI Error (F)'] = round(post_tdai_error, 2)
                    log_row['TdAI Skill Score (%)'] = round(hour_skill_score, 1)

                    # Print Text Verification Report
                    print("\n" + "═"*90)
                    print(f"📊 POST-EVENT VERIFICATION DISPATCH REPORT FOR KCAR (VALID: {forecast_valid_time.strftime('%Y-%m-%d %H:%M UTC')})")
                    print("═"*90)
                    print(f"   🔹 Observed ASOS Ground Truth Dewpoint : {asos_ground_truth:.1f}°F")
                    print(f"   🔹 Original NBM Baseline Dewpoint       : {log_row['NBM Dewpoint (F)']:.1f}°F  (Error: {raw_nbm_error:+.1f}°F)")
                    print(f"   🔹 TdAI Post-Processed Dewpoint         : {log_row['TdAI Corrected Dewpoint (F)']:.1f}°F  (Error: {post_tdai_error:+.1f}°F)")
                    print("   " + "─"*84)

                    if abs_tdai < abs_nbm:
                        print(f"   🚀 SUCCESS: TdAI trimmed forecast error by {abs_nbm - abs_tdai:.1f}°F ({hour_skill_score:.1f}% Improvement).")
                    elif abs_tdai == abs_nbm:
                        print(f"   🤝 TIE: TdAI matched the baseline NBM forecast exactly.")
                    else:
                        print(f"   ⚠️ OVER-CORRECTION: TdAI increased error by {abs_tdai - abs_nbm:.1f}°F at this specific hour setup.")
                    print("═"*90)

    except Exception as e:
        print(f"   ❌ Network error during ASOS validation query: {e}")
        print("   └── Action: Proceeding to log forecast fields only.")
        has_valid_verification = False

# =====================================================================
# 💾 TdAI DATA AND PERFORMANCE LOGGING
# =====================================================================
if run_logging:
    # Convert our current active run dictionary into a structured 1-row DataFrame
    new_entry_df = pd.DataFrame([log_row])

    if os.path.exists(output_csv_path):
        try:
            # Read your running history from Google Drive
            existing_log_df = pd.read_csv(output_csv_path)

            # Enforce matching string serialization for the deduplication key
            existing_log_df['valid_time'] = pd.to_datetime(existing_log_df['valid_time']).dt.strftime('%Y-%m-%d %H:%M:%S')

            # Stack the historical data and the current run on top of each other
            combined_log_df = pd.concat([existing_log_df, new_entry_df], ignore_index=True)

            # 🚀 DEDUPLICATION GUARD: Keep only the LAST row for any given valid_time.
            # This allows a verified run to seamlessly overwrite a previous 'Standby' run.
            combined_log_df = combined_log_df.drop_duplicates(subset=['valid_time'], keep='last')
        except Exception as e:
            print(f"⚠️ Warning: Issue reading existing database log file. Resetting ledger: {e}")
            combined_log_df = new_entry_df
    else:
        print(f"📝 Initializing a brand new persistent verification log on Drive.")
        combined_log_df = new_entry_df

    # Write the updated dataframe back to Google Drive
    combined_log_df.to_csv(output_csv_path, index=False)
    print(f"💾 Drive Log Updated! Path: {output_csv_path}")
    print(f"   └── Total unique logged forecast days archived: {len(combined_log_df)}\n")

print("\n📊 Initializing Automated Forecast Validation Engine...")

# 1. Extract the current row's valid time and the current time in UTC
forecast_valid_time = master_input_df['valid_time'].iloc[0]
current_time_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)

print(f"   └── Forecast valid time : {forecast_valid_time.strftime('%Y-%m-%d %H:%M UTC')}")
print(f"   └── System clock time   : {current_time_utc.strftime('%Y-%m-%d %H:%M UTC')}")

# 2. Check if the target hour has actually occurred yet
if current_time_utc < forecast_valid_time + datetime.timedelta(minutes=15):
    print("\n⏳ Verification Status: STANDBY")
    print(f"   └── Reason: The forecast validation window has not been reached yet.")
    print(f"   └── Note  : ASOS validation will become available once the system clock passes the valid window.")
else:
    print("\n📡 Forecast hour is in the past. Fetching KCAR ASOS ground-truth observation...")

    # Configure the IEM ASOS API request window (pulling a 2-day buffer centered on valid_time)
    start_date = forecast_valid_time - datetime.timedelta(days=1)
    end_date = forecast_valid_time + datetime.timedelta(days=1)

    station_iem = 'CAR'

    asos_url = (
        f"https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?"
        f"station={station_iem}&data=dwpf&"
        f"year1={start_date.year}&month1={start_date.month}&day1={start_date.day}&"
        f"year2={end_date.year}&month2={end_date.month}&day2={end_date.day}&"
        f"tz=UTC&format=comma"
    )

    try:
        response = requests.get(asos_url, timeout=20)
        response.raise_for_status()

        # Read the text stream directly into a Pandas DataFrame, ignoring comment lines (#)
        asos_df = pd.read_csv(io.StringIO(response.text), comment='#')

        if asos_df.empty or 'dwpf' not in asos_df.columns:
            print("   ⚠️ Warning: Connected to IEM registry, but no observations were found for this window.")
        else:
            # Cleanse and parse time fields to line up with the 21Z hourly round
            asos_df['valid_dt'] = pd.to_datetime(asos_df['valid'])
            asos_df['rounded_valid_time'] = asos_df['valid_dt'].dt.round('h')

            # Isolate all reports that round to our target convective hour
            target_obs = asos_df[asos_df['rounded_valid_time'] == forecast_valid_time].copy()

            if target_obs.empty:
                print(f"   ⚠️ Warning: ASOS data found for this date, but the specific 21Z observation row was missing.")
            else:
                # 🚀 FIX A: Force 'dwpf' to numeric values, turning 'M' text strings into np.nan
                target_obs['dwpf_numeric'] = pd.to_numeric(target_obs['dwpf'], errors='coerce')

                # 🚀 FIX B: Drop rows where the dewpoint metric is missing
                valid_reports = target_obs.dropna(subset=['dwpf_numeric'])

                if valid_reports.empty:
                    # If EVERY report in that hour block is genuinely missing/unrecorded
                    raw_dwpf = target_obs['dwpf'].iloc[0]
                    print(f"   ⚠️ Warning: All KCAR observations at this hour are missing or unreadable ('{raw_dwpf}').")
                    print(f"       [Note: This is likely due to current-day database ingestion lag on the IEM server.]")
                    has_valid_verification = False
                else:
                    # 🚀 FIX C: Extract the first available report that has a valid, readable dewpoint
                    asos_ground_truth = valid_reports['dwpf_numeric'].iloc[0]
                    has_valid_verification = True

                if has_valid_verification:
                    # METEOROLOGICAL METRIC VERIFICATION GENERATION
                    nbm_dewpoint = master_input_df['NBM Dewpoint (F)'].iloc[0]
                    tdai_dewpoint = master_input_df['TdAI Corrected Dewpoint (F)'].iloc[0]

                    # Compute absolute deviations from ground truth
                    raw_nbm_error = nbm_dewpoint - asos_ground_truth
                    post_tdai_error = tdai_dewpoint - asos_ground_truth

                    abs_nbm_error = abs(raw_nbm_error)
                    abs_tdai_error = abs(post_tdai_error)

                    if abs_nbm_error > 0:
                        hour_skill_score = (1.0 - (abs_tdai_error / abs_nbm_error)) * 100
                    else:
                        hour_skill_score = 0.0

                    # PRINT VERIFICATION REPORT
                    print("\n" + "═"*90)
                    print(f"📊 POST-EVENT VERIFICATION DISPATCH REPORT FOR KCAR (VALID: {forecast_valid_time.strftime('%Y-%m-%d %H:%M UTC')})")
                    print("═"*90)
                    print(f"   🔹 Observed ASOS Ground Truth Dewpoint : {asos_ground_truth:.1f}°F")
                    print(f"   🔹 Original NBM Baseline Dewpoint       : {nbm_dewpoint:.1f}°F  (Error: {raw_nbm_error:+.1f}°F)")
                    print(f"   🔹 TdAI Post-Processed Dewpoint         : {tdai_dewpoint:.1f}°F  (Error: {post_tdai_error:+.1f}°F)")
                    print("   " + "─"*84)

                    if abs_tdai_error < abs_nbm_error:
                        print(f"   🚀 SUCCESS: TdAI trimmed forecast error by {abs_nbm_error - abs_tdai_error:.1f}°F ({hour_skill_score:.1f}% Improvement).")
                    elif abs_tdai_error == abs_nbm_error:
                        print(f"   🤝 TIE: TdAI matched the baseline NBM forecast exactly.")
                    else:
                        print(f"   ⚠️ OVER-CORRECTION: TdAI increased error by {abs_tdai_error - abs_nbm_error:.1f}°F at this specific hour setup.")
                    print("═"*90)

    except Exception as e:
        print(f"   ❌ Network error during ASOS validation query: {e}")